name: Tag and Mention

on:
  push:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: node tag-and-mention.mjs 診断メーカー
        env:
          MASTODON_HOST: ${{ secrets.MASTODON_HOST }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
